// Opt-in live test: backend/frontend must be running; uses real OpenAI credits.
const assert = require('node:assert/strict');
const path = require('node:path');
const os = require('node:os');
const { chromium } = require('playwright-core');

(async () => {
  const browser = await chromium.launch({ channel: process.env.BROWSER_CHANNEL || 'msedge', headless: true });
  try {
    const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
    const errors = [];
    let confirmationRequests = 0;
    page.on('request', request => { if (request.url() === 'http://localhost:3000/api/cart/confirm') confirmationRequests++; });
    page.on('pageerror', () => errors.push('Browser JavaScript error'));
    await page.goto(process.env.FRONTEND_URL || 'http://localhost:4173', { waitUntil: 'domcontentloaded' });
    assert.equal(await page.locator('.product-card').count(), 0);
    assert.doesNotMatch(await page.locator('body').innerText(), /ИИ не подключён|тестовые товары|тестовый ответ/i);
    async function ask(message) {
      await page.locator('#message-input').fill(message);
      const responsePromise = page.waitForResponse(r => r.url() === 'http://localhost:3000/api/chat' && r.request().method() === 'POST', { timeout: 160000 });
      await page.locator('#send-button').click();
      const response = await responsePromise;
      assert.equal(response.request().postDataJSON().message, message);
      const body = await response.json();
      console.log(JSON.stringify({ request: message, httpStatus: response.status(), code: body.error?.code, productIds: body.products?.map(p => p.id) }));
      assert.equal(response.status(), 200, 'Live chat must respond with HTTP 200');
      await page.locator('#connection-status').filter({ hasText: 'Ответ получен от AI' }).waitFor();
      assert.equal(await page.locator('.message-assistant').last().locator('.message-text').innerText(), body.message);
      assert.equal(await page.locator('.message-assistant').last().locator('.product-card').count(), body.products.length);
      return body;
    }
    const answer = await ask('Есть Legrand 40A?');
    assert.ok(answer.products.length > 0, 'Expected real matching products');
    const item = answer.products.find(p => p.quantity >= 1) || answer.products[0];
    assert.ok(Number.isSafeInteger(item.id));
    const button = page.locator(`[data-product-id="${item.id}"]`).last();
    const detailPromise = page.waitForResponse(r => r.url() === 'http://localhost:3000/api/cart/proposals');
    await button.click();
    const detailResponse = await detailPromise;
    assert.equal(detailResponse.status(), 201);
    const detail = (await detailResponse.json()).items[0].product;
    assert.ok(detail.quantity >= 1, 'Need an in-stock product for the confirmation flow');
    await page.locator('#confirm-dialog[open]').waitFor();
    const stock = Math.floor(detail.quantity);
    assert.equal(await page.locator('#cart-count').innerText(), '0');
    const quantity = Math.min(2, stock);
    await page.locator('#quantity-input').fill(String(quantity));
    assert.equal(await page.locator('#cart-count').innerText(), '0');
    await page.locator('#cancel-confirmation').click();
    await page.locator('#confirm-dialog').waitFor({ state: 'hidden' });
    assert.equal(confirmationRequests, 0);
    assert.equal(await page.locator('#cart-count').innerText(), '0');
    await button.click();
    await page.locator('#confirm-dialog[open]').waitFor();
    await page.locator('#quantity-input').fill(String(stock + 1));
    assert.equal(await page.locator('#confirm-button').isDisabled(), true);
    assert.equal(await page.locator('#cart-count').innerText(), '0');
    assert.match(await page.locator('#quantity-error').innerText(), /Доступно/);
    await page.locator('#quantity-input').fill(String(quantity));
    assert.equal(confirmationRequests, 0);
    const confirmedResponse = page.waitForResponse(r => r.url() === 'http://localhost:3000/api/cart/confirm');
    await page.locator('#confirm-button').click();
    await page.locator('#confirm-dialog').waitFor({ state: 'hidden' });
    assert.equal(await page.locator('#cart-count').innerText(), String(quantity));
    assert.equal(await page.locator('#cart-items .cart-item h3').innerText(), detail.name);
    const confirmed = await (await confirmedResponse).json();
    await page.evaluate(id => window.EktApp.confirmCart(id), confirmed.proposalId);
    assert.equal(await page.evaluate(async () => (await window.EktApp.getCart()).totalCount), quantity);
    await page.locator('.cart-shortcut').click();
    assert.equal(await page.locator('#header-cart-count').innerText(), String(quantity));
    await page.screenshot({ path: path.join(os.tmpdir(), 'ekt-integration-desktop.png'), fullPage: true });
    const unknown = await ask('Расскажи про несуществующий товар XYZ123NOTFOUND');
    assert.equal(unknown.products.length, 0);
    assert.match(unknown.message, /Не удалось найти подходящий товар/);
    assert.equal(await page.locator('#cart-count').innerText(), String(quantity));
    // The existing Revisor shares the server cart; its selection/audit logic is unchanged.
    await page.locator('[data-view="audit"]').click();
    const auditText = '200300273_ ; 2\nXYZ123NOTFOUND ; 3';
    await page.locator('#audit-input').fill(auditText);
    let auditResponse = page.waitForResponse(r => r.url() === 'http://localhost:3000/api/audit', { timeout: 150000 });
    await page.locator('#audit-submit').click();
    let response = await auditResponse;
    assert.equal(response.status(), 200);
    const report = await response.json();
    assert.equal(report.data_mode, 'live');
    assert.equal(report.rows[0].status, 'ready');
    assert.equal(report.rows[0].product.id, 515279);
    assert.ok(typeof report.rows[0].product.price === 'number');
    assert.ok(report.rows[0].product.stock >= 2);
    assert.equal(report.rows[1].status, 'not_found');
    await page.locator('[data-select-row="row-1"]').waitFor();
    assert.equal(await page.locator('#cart-count').innerText(), String(quantity));
    assert.equal(await page.locator('[data-select-row="row-2"]').isDisabled(), true);
    await page.locator('[data-select-row="row-1"]').check();
    assert.equal(await page.locator('#cart-count').innerText(), String(quantity));
    await page.locator('#prepare-list').click();
    await page.locator('#batch-dialog[open]').waitFor();
    assert.equal(await page.locator('#cart-count').innerText(), String(quantity));
    await page.locator('#batch-cancel').click();
    await page.locator('#batch-dialog').waitFor({ state: 'hidden' });
    assert.equal(await page.locator('#cart-count').innerText(), String(quantity));
    await page.locator('#prepare-list').click();
    await page.locator('#batch-dialog[open]').waitFor();
    await page.locator('#batch-confirm').click();
    await page.locator('#batch-dialog').waitFor({ state: 'hidden', timeout: 30000 });
    assert.equal(await page.locator('#cart-count').innerText(), String(quantity + 2));
    await page.screenshot({ path: path.join(os.tmpdir(), 'ekt-revisor-confirmed.png'), fullPage: true });
    await page.locator('#audit-input').fill(`200300273_ ; ${Math.floor(report.rows[0].product.stock) + 1}`);
    auditResponse = page.waitForResponse(r => r.url() === 'http://localhost:3000/api/audit', { timeout: 150000 });
    await page.locator('#audit-submit').click();
    response = await auditResponse;
    assert.equal(response.status(), 200);
    const shortage = await response.json();
    assert.equal(shortage.rows[0].status, 'shortage');
    await page.locator('.audit-row[data-status="shortage"]').waitFor();
    assert.equal(await page.locator('[data-select-row="row-1"]').isDisabled(), true);
    assert.equal(await page.locator('#prepare-list').isDisabled(), true);
    assert.equal(await page.locator('#cart-count').innerText(), String(quantity + 2));
    console.log(JSON.stringify({ audit: 'passed', statuses: report.rows.map(row => row.status), price: report.rows[0].product.price, stock: report.rows[0].product.stock, quantityAddedAfterConfirmation: 2, shortageBlocked: true }));
    await page.reload({ waitUntil: 'domcontentloaded' });
    await page.waitForFunction(count => document.getElementById('cart-count').textContent === String(count), quantity + 2);
    assert.equal(await page.evaluate(async () => (await window.EktApp.getCart()).totalCount), quantity + 2);
    console.log(JSON.stringify({ serverCart: 'passed', reloadPreserved: true, repeatedConfirmDidNotDuplicate: true }));
    await page.setViewportSize({ width: 390, height: 844 });
    assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), 'No horizontal overflow on mobile');
    await page.screenshot({ path: path.join(os.tmpdir(), 'ekt-integration-mobile.png'), fullPage: true });
    assert.equal(errors.length, 0);
    console.log(JSON.stringify({ passed: true, confirmedProductId: item.id, quantity, stock, cartBeforeConfirmation: 0, overStockBlocked: true, unknownProducts: 0, browserErrors: errors.length, screenshots: os.tmpdir() }));
  } finally { await browser.close(); }
})().catch(error => { console.error('Browser smoke failed: ' + error.message); process.exitCode = 1; });
